version: '3'

services:
  bikesapp:
    image: nbondarenko/bikes-app:latest
    container_name: bikesapp
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - bookingapp
    links:
      - mongo
      - bookingapp

  bookingapp:
    image: nbondarenko/bookings-app:latest
    container_name: bookingapp
    restart: always
    ports:
      - 3000:5001
    depends_on:
      - mongo
    links:
      - mongo


  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
